### ISSUE TITLE
Black Adam clarifications

### ISSUE THREAD

**Issue by Arkandos** [Freeman322/CHW_translation#19]
- [ ] Q - Explain how the damage works.
- [ ] W - Re-phrasing.
- [ ] E - Clarifications how it works.
- [ ] R - Change tooltip to reflect how much damage it actually does.

**Comment by Freeman322** [comment]
This hero will be fully reworked soon

**Comment by Arkandos** [comment]
Then I will just close this?

**Comment by Freeman322** [comment]
Yep)
